# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ecdb7fc11aa4477116ebbf7e72a56f9425c743167d9b958e516848d2275d42021e25c55e508c69aed162cdde36cd0f6f7f6ca27f0ebdb0a63d55dda23aea5ae

test:
  secret_key_base: 8eff6700b14c77beb3a1ad3e91dabec587a29b7c4e83409bfc3f5c80dfb123abd7979c04a1214ddf81b2fa0b83f70071d2bbf84e8d1ec56f98e526fcd2f246cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
